# GitHub Sponsors Configuration
# Support this project

# GitHub Sponsors (uncomment if you enable GitHub Sponsors)
# github: [dearmydear]

# Custom donation links
# Direct link to Alipay donation QR code
custom: ['https://github.com/dearmydear/call-graph-editor#donate']
